baseURL = "https://www.commerble.com/docs/"
languageCode = "ja-JP"
title = "Commerble Docs"
theme = "docsy"

# Will give values to .Lastmod etc.
enableGitInfo = true

defaultContentLanguage = "ja"
copyright = "this is sample"

# (Optional) Set Google Analytics if you use it to track your website.
# Always put it on the top of the configuration file, otherwise it won't work
googleAnalytics = "UA-58587912-1"

[params]
time_format_default = "2006-01-02"


[params.mermaid]
enable = true
theme = "neutral"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      # guessSyntax = "true"


[[menu.main]]
  name = "HOME"
  weight = 50
  url = "https://www.commerble.com/"
