baseURL = "https://www.commerble.com/docs/"
languageCode = "ja-JP"
title = "Commerble Docs"

enableRobotsTXT = true

# Will give values to .Lastmod etc.
enableGitInfo = true

defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false

googleAnalytics = "UA-58587912-1"

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true


[services]
[services.googleAnalytics]
id = "UA-58587912-1"

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "011737558837375720776:fsdu1nryfng"
gcs_engine_id = "f468d8f73b829f44e"

[params]
  description = "Commerbleは、Eコマースシステムが顧客ごとに異なる業務設計で運用されていることを前提に設計された、顧客固有の要件に柔軟かつ短納期で対応できるカスタマイズ性の高いECプラットフォームです。"
  author = "Commerble Inc."
  keywords = ["EC", "ecommerce", "B2C", "B2B", "D2C", "基幹連携"]
  image = "/images/ogp.png"

  [params.contact]
    email = "info@commerble.com"
    phone = "03-6661-1334"
    address = "東京都中央区日本橋蛎殻町1-12-9 カモツル日本橋ビル 3F"

  [params.features]
    darkMode = true

  [params.mermaid]
    enable = true
    theme = "neutral"


[menu]
  [[menu.main]]
    name = "会社概要"
    url = "https://www.commerble.com/about/"
    weight = 45
  [[menu.main]]
    name = "サービス"
    url = "https://www.commerble.com/features/"
    weight = 30
  [[menu.main]]
    name = "利用料金"
    url = "https://www.commerble.com/pricing/"
    weight = 35
  [[menu.main]]
    name = "最新情報"
    url = "https://www.commerble.com/contents/"
    weight = 40
  [[menu.main]]
    name = "お問い合わせ"
    url = "https://www.commerble.com/contact/"
    weight = 50
  [[menu.main]]
    name = "ドキュメント"
    url = "/"
    weight = 32

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    codeFences = true
