baseURL = "https://www.commerble.com/docs/"
languageCode = "ja-JP"
title = "Commerble Docs"
theme = "docsy"

enableRobotsTXT = true

# Will give values to .Lastmod etc.
enableGitInfo = true

defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false

googleAnalytics = "UA-58587912-1"

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true


[services]
[services.googleAnalytics]
id = "UA-58587912-1"

[params]
time_format_default = "2006-01-02"
copyright = "Commerble Inc. "

baseUrl = "https://www.commerble.com/docs/"

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "011737558837375720776:fsdu1nryfng"
gcs_engine_id = "f468d8f73b829f44e"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = false

prism_syntax_highlighting = true

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = false
# Set to true to disable the About link in the site footer
footer_about_disable = false


[params.mermaid]
enable = true
theme = "neutral"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "tango"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      # guessSyntax = "true"


[[menu.main]]
  name = "HOME"
  weight = 50
  url = "https://www.commerble.com/"
