baseURL = "https://www.commerble.com/docs/"
languageCode = "ja-JP"
title = "Commerble Docs"
theme = "docsy"

[[menu.main]]
    name = "HOME"
    weight = 50
    url = "https://www.commerble.com/"

relativeURLs = true

defaultContentLanguage = "ja"
copyright = "this is sample"

# Book configuration
disablePathToLower = true
enableGitInfo = true

# (Optional) Set Google Analytics if you use it to track your website.
# Always put it on the top of the configuration file, otherwise it won't work
googleAnalytics = "UA-58587912-1"

[params.mermaid]
enable = true
theme = "neutral"

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[menu]
# [[menu.before]]
# [[menu.after]]
#   name = "Github"
#   url = "https://github.com/commerble/docs"



[params]
